apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - mediaz.yaml
  - sealedsecret.yaml

images:
  - name: mediaz
    newName: ghcr.io/kasuboski/mediaz
    newTag: sha-b16d17e47f63a733ded372c13ba0bd6f73012e8b
