apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - mediaz.yaml
  - sealedsecret.yaml

images:
  - name: mediaz
    newName: ghcr.io/kasuboski/mediaz
    newTag: sha-94358bd2ae7035d41b062f19e33a3748a6c992bb
