apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - constellation.yaml
  - envoy-bouncer.yaml
  # - envoy-proxy-gatekeeper.yaml
  - namespace.yaml
  - crowdsec.yaml
  - vpa.yaml
