apiVersion: v2
name: tailscale
description: tailscale
version: 0.1.0
dependencies:
  - name: tailscale-operator
    version: ^1.0.0
    repository: https://pkgs.tailscale.com/helmcharts
  - name: homelab-chart
    version: ^0.1.0
    repository: https://kdwils.github.io/helm-charts
    alias: homelab
