apiVersion: v2
name: tailscale
description: tailscale
version: 0.1.0
dependencies:
  - name: tailscale-operator
    version: 1.90.6
    repository: https://pkgs.tailscale.com/helmcharts
    alias: tailscale
  - name: homelab-chart
    version: 0.1.6
    repository: https://kdwils.github.io/helm-charts
    alias: homelab
