apiVersion: v2
name: overseerr
description: overseerr
version: 0.1.0
dependencies:
  - name: homelab-chart
    version: 0.1.1
    repository: https://kdwils.github.io/helm-charts
    alias: overseerr
