resources:
  - update-source-main.yaml
  - render-single-app.yaml
  - render-all-apps.yaml
  - render-and-pr-helm.yaml
  - update-helm-charts.yaml
  - git-ops-clone.yaml
  - git-ops-commit-pr.yaml
  - helm-update-single-chart.yaml
