apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - update-source-main.yaml
  - render-and-pr-helm.yaml
  - update-helm-charts.yaml
  - git-ops-clone.yaml
  - git-ops-commit-pr.yaml
  - helm-update-single-chart.yaml
