apiVersion: v2
name: envoy-proxy-bouncer
description: Envoy proxy bouncer with homelab-chart
version: 0.1.0
dependencies:
  - name: envoy-proxy-bouncer
    version: 0.5.1
    repository: https://kdwils.github.io/envoy-proxy-crowdsec-bouncer
    alias: homelab-envoy-proxy-bouncer
  - name: homelab-chart
    version: 0.1.13
    repository: https://kdwils.github.io/helm-charts
    alias: homelab
