apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - argocd.yaml
  - bazarr.yaml
  - blog.yaml
  - bluesky.yaml
  - byparr.yaml
  - cloudflared.yaml
  - envoy-proxy-bouncer.yaml
  - envoy-proxy-gatekeeper.yaml
  - events.yaml
  - kargo.yaml
  - homelab-project.yaml
  - homelab-chart.yaml
  - longhorn.yaml
  - mealie.yaml
  - nats.yaml
  - openclaw.yaml
  - overseerr.yaml
  - plex.yaml
  - pocketid.yaml
  - prowlarr.yaml
  - radarr.yaml
  - rss.yaml
  - sealedsecrets.yaml
  - sonarr.yaml
  - tailscale.yaml
  - transmission.yaml
