apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # - constellation.yaml
  - namespace.yaml

images:
  - name: constellation
    newName: ghcr.io/kdwils/constellation
    newTag: sha-f1f0b28fa11d8574aafc62cccb91461e8732bf97
