apiVersion: v2
name: envoy-proxy-bouncer
description: envoy-proxy-bouncer
version: 0.1.0
dependencies:
  - name: envoy-proxy-bouncer
    version: 0.4.1
    repository: https://kdwils.github.io/envoy-proxy-crowdsec-bouncer
    alias: homelab-envoy-proxy-bouncer
  - name: homelab-chart
    version: 0.1.4
    repository: https://kdwils.github.io/helm-charts
    alias: homelab
