apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - blog.yaml
  - bluesky.yaml
  - rss.yaml
  - mealie.yaml
  - overseerr.yaml
  - pocketid.yaml
  - radarr.yaml
  - sonarr.yaml
