apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - bazarr.yaml
  - blog.yaml
  - bluesky.yaml
  - cloudflared.yaml
  - envoy-proxy-bouncer.yaml
  # - excalidraw.yaml
  - flaresolverr.yaml
  - homelab-chart.yaml
  - mealie.yaml
  - overseerr.yaml
  - plex.yaml
  - pocketid.yaml
  - prowlarr.yaml
  - radarr.yaml
  - rss.yaml
  - sonarr.yaml
