apiVersion: v2
name: longhorn
description: kargo
version: 0.1.0
dependencies:
  - name: kargo
    version: 1.9.2
    repository: oci://ghcr.io/akuity/kargo-charts
    alias: kargo
  - name: homelab-chart
    version: 0.1.12
    repository: https://kdwils.github.io/helm-charts
    alias: homelab
