apiVersion: v2
name: longhorn
description: kargo
version: 0.1.0
dependencies:
  - name: kargo
    version: 0.0.0
    repository: oci://ghcr.io/akuity/kargo-charts
    alias: kargo
  - name: homelab-chart
    version: 0.1.9
    repository: https://kdwils.github.io/helm-charts
    alias: homelab
