apiVersion: v2
name: homelab
description: A set of helm charts for deploying to my homelab
version: 0.1.0
dependencies:
  - name: homelab-chart
    version: 0.0.12
    repository: https://kdwils.github.io/helm-charts
