apiVersion: kargo.akuity.io/v1alpha1
kind: ClusterPromotionTask
metadata:
  name: update-source-main
spec:
  vars:
    - name: gitRepo
      value: https://github.com/kdwils/homelab
    - name: targetBranch
      value: main
    - name: warehouse
    - name: imageRepo
    - name: valuesFilePath
    - name: imageTagYamlPath
  steps:
    - uses: git-clone
      as: clone-main
      config:
        repoURL: ${{ vars.gitRepo }}
        checkout:
          - branch: ${{ vars.targetBranch }}
            path: ./repo
    - uses: yaml-update
      as: update-image-tag
      config:
        path: ./repo/${{ vars.valuesFilePath }}
        updates:
          - key: ${{ vars.imageTagYamlPath }}
            value: ${{ imageFrom(vars.imageRepo, warehouse(vars.warehouse)).Tag }}
    - uses: git-commit
      as: commit-updates
      config:
        path: ./repo
        message: |
          Update image version
          - Image: ${{ imageFrom(vars.imageRepo, warehouse(vars.warehouse)).Tag }}
    - uses: git-push
      as: push-feature-branch
      config:
        path: ./repo
        generateTargetBranch: true
    - uses: git-open-pr
      as: open-pr-main
      continueOnError: true
      config:
        repoURL: ${{ vars.gitRepo }}
        sourceBranch: ${{ task.outputs['push-feature-branch'].branch }}
        targetBranch: ${{ vars.targetBranch }}
        createTargetBranch: false
        title: "Update image version"
        description: |
          ## Updates
          - **Image:** `${{ imageFrom(vars.imageRepo, warehouse(vars.warehouse)).Tag }}`
          Updated via Kargo promotion from warehouse: ${{ vars.warehouse }}
    - uses: git-wait-for-pr
      as: wait-pr-approval
      if: ${{ status('open-pr-main') == 'Succeeded' }}
      config:
        repoURL: ${{ vars.gitRepo }}
        prNumber: ${{ task.outputs['open-pr-main'].pr.id }}
