apiVersion: v2
name: seerr
description: Seerr media request platform with homelab chart for HTTPRoute and SecurityPolicy
version: 0.1.0
dependencies:
  - name: seerr-chart
    version: 2.2.0
    repository: oci://ghcr.io/seerr-team/seerr
  - name: homelab-chart
    version: 0.1.13
    repository: https://kdwils.github.io/helm-charts
    alias: homelab
