resources:
  - blog.yaml
  - bluesky.yaml
  - clickhouse.yaml
  - events.yaml
  - excalidraw.yaml
  - hoarder.yaml
  - kargo.yaml
  - mealie.yaml
  - minio.yaml
  - nats.yaml
  - pocketid.yaml
  - vaultwarden.yaml
  - rss.yaml
