apiVersion: v2
name: argocd
description: ArgoCD GitOps controller
version: 0.1.0
dependencies:
  - name: argo-cd
    version: 7.7.16
    repository: https://argoproj.github.io/argo-helm
    alias: argocd
  - name: homelab-chart
    version: 0.0.14
    repository: https://kdwils.github.io/helm-charts
    alias: homelab
